// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabaseConfigError: string | null =
  !SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY
    ? 'App configuration is incomplete. The database connection settings are missing — please republish the app or contact support.'
    : null;

function createGuardedClient(): SupabaseClient<Database> {
  if (supabaseConfigError) {
    // Return a proxy that only throws when actually used, so the app can
    // mount and show a friendly error instead of crashing at startup.
    return new Proxy({} as SupabaseClient<Database>, {
      get(_target, prop) {
        if (prop === 'then') return undefined; // keep it non-thenable
        throw new Error(supabaseConfigError);
      },
    });
  }
  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

export const supabase = createGuardedClient();
